In [1]:
print('hello world')

hello world


### Array operation




In [3]:
2**32

4294967296

In [4]:
import numpy as np

In [5]:
num=np.array([56,23,11,67,42,38,64])

In [9]:
print(num)

[56.   23.   11.   67.   42.38 64.  ]


In [7]:
num

array([56.  , 23.  , 11.  , 67.  , 42.38, 64.  ])

In [8]:
num.dtype

dtype('float64')

In [10]:
num.size

6

In [11]:
num[3]

67.0

In [17]:
num[3] = 35
num

array([56.  , 23.  , 11.  , 35.  , 42.38, 64.  ])

In [19]:
num = np.array([56,23,11,67,42,38,True])
num

array([56, 23, 11, 67, 42, 38,  1])

In [20]:
num = np.array([56,23,11,67,'hello,',38,64])

In [21]:
num

array(['56', '23', '11', '67', 'hello,', '38', '64'], dtype='<U11')

In [1]:
city = np.array(['पुणे ','नागपूर ','नाशिक ','अकोला '])

NameError: name 'np' is not defined

In [2]:
city

NameError: name 'city' is not defined

In [3]:
x=[56,23,11,67,42,38,64]
x*2

[56, 23, 11, 67, 42, 38, 64, 56, 23, 11, 67, 42, 38, 64]

In [4]:
num *2

NameError: name 'num' is not defined

In [5]:
import numpy as np

In [6]:
num=np.array([56,23,11,67,42,38,64])

In [7]:
print(num)

[56 23 11 67 42 38 64]


In [8]:
num *2

array([112,  46,  22, 134,  84,  76, 128])

In [9]:
num/10

array([5.6, 2.3, 1.1, 6.7, 4.2, 3.8, 6.4])

In [10]:
num-10

array([46, 13,  1, 57, 32, 28, 54])

In [11]:
num>40

array([ True, False, False,  True,  True, False,  True])

In [12]:
42 in num

True

In [13]:
89 not in num

True

In [14]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [15]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [16]:
list(range(10,0,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
np.arange(20,0,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [21]:
np.arange(1,10,0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [22]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(14)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.empty(10)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [25]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [28]:
x = np.array([[4,5,6],[8,9,1]])

In [29]:
x

array([[4, 5, 6],
       [8, 9, 1]])

In [30]:
x.shape

(2, 3)

In [31]:
x.size

6

In [32]:
x.ndim

2

In [33]:
x[1][2]

1

In [34]:
x.reshape(3,2)

array([[4, 5],
       [6, 8],
       [9, 1]])

In [35]:
x.reshape(6,1)

array([[4],
       [5],
       [6],
       [8],
       [9],
       [1]])

In [36]:
x.reshape(-1,2)

array([[4, 5],
       [6, 8],
       [9, 1]])

In [37]:
x.flatten()

array([4, 5, 6, 8, 9, 1])

### Serise Operation

In [39]:
import pandas as pd

In [40]:
s = pd.Series([56,23,16,38,61,93])

In [41]:
s

0    56
1    23
2    16
3    38
4    61
5    93
dtype: int64

In [42]:
s[2]

16

In [43]:
s[2]=29

In [44]:
s

0    56
1    23
2    29
3    38
4    61
5    93
dtype: int64

In [45]:
s = pd.Series([56,23,16,38,61,93], index = range(100,106))

In [46]:
s

100    56
101    23
102    16
103    38
104    61
105    93
dtype: int64

In [47]:
s[104]

61

In [48]:
s.dtype

dtype('int64')

In [49]:
s.size

6

### DataFrame Operation

In [57]:
x = pd.Series([1,2,3,4,5])
y = pd.Series(['Ajay','Ram','Priya','Anita','Ashok'])
z = pd.Series([67.89,56.12,74.65,61.23,69.99])

In [58]:
df = pd.DataFrame({
    'roll' : x,
    'name' : y,
    'marks' : z,
})

In [59]:
df

roll   name  marks
0     1   Ajay  67.89
1     2    Ram  56.12
2     3  Priya  74.65
3     4  Anita  61.23
4     5  Ashok  69.99

In [60]:
df.shape

(5, 3)

In [62]:
df.columns

Index(['roll', 'name', 'marks'], dtype='object')

In [63]:
df.size

15

In [64]:
df.T

0      1      2      3      4
roll       1      2      3      4      5
name    Ajay    Ram  Priya  Anita  Ashok
marks  67.89  56.12  74.65  61.23  69.99

In [65]:
list(s)

[56, 23, 16, 38, 61, 93]

In [66]:
tuple(s)

(56, 23, 16, 38, 61, 93)

In [67]:
set(s)

{16, 23, 38, 56, 61, 93}

In [68]:
s.values

array([56, 23, 16, 38, 61, 93], dtype=int64)

In [69]:
df.values

array([[1, 'Ajay', 67.89],
       [2, 'Ram', 56.12],
       [3, 'Priya', 74.65],
       [4, 'Anita', 61.23],
       [5, 'Ashok', 69.99]], dtype=object)

In [70]:
dict(df)

{'roll': 0    1
 1    2
 2    3
 3    4
 4    5
 Name: roll, dtype: int64,
 'name': 0     Ajay
 1      Ram
 2    Priya
 3    Anita
 4    Ashok
 Name: name, dtype: object,
 'marks': 0    67.89
 1    56.12
 2    74.65
 3    61.23
 4    69.99
 Name: marks, dtype: float64}

In [78]:
x=np.arange(1,101)

In [74]:
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [75]:
y= np.array([79,92,3,37,48])

In [76]:
x.mean()

50.5

In [77]:
y.mean()

51.8